type Query {
  orders(id: Int): [Order]
  items: [Item],
  getItemById(id: Int): Item 
}

type Order {
  items: [Item]
  notes: [Note]
  seller: Vendor
  tax: Int
  shipping: Int
}

type Vendor {
  name: String
  url: String
}

type Image {
  url: String
  name: String
  description: String
}

type Note {
  content: String
  createdAt: String
  updatedAt: String
}

type Category {
  name: String
  icon: String
  description: String
  createdAt: String
}

type Item {
  name: String
  description: String
  attributes: ItemAttributes
  category: Category
  qty: Int
  images: [Image]
  notes: [Note]
  priceHistory: [PriceHistory]
}

type ItemAttributes {
  colorway: String
  maker: String
  model: String
}

type PriceHistory {
  updateType: String
  price: String
  createdAt: String
}