name: Cypress Tests

on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env:
      TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
      S3_ACESSS_SECRET: ${{ secrets.S3_ACESSS_SECRET }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      CYPRESS_MAILSLURP_API_KEY: ${{ secrets.CYPRESS_MAILSLURP_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm start
