name: Cypress Tests

on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm start
      - name: Artifacts
        uses: actions/upload-artifact@v2
          if: always()
          with:
            name: cypress-coverage
            path: coverage
        uses: actions/upload-artifact@v2
          if: failure()
          with:
            name: cypress-screenshots
            path: cypress/screenshots
        uses: actions/upload-artifact@v2
          if: failure()
          with:
            name: cypress-videos
            path: cypress/videos